name: ADRs page

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  adr-view-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install adr-viewer and create index.html
        run: |
          pip install adr-viewer
          mkdir public
          adr-viewer --output public/index.html

      - name: Deploy github pages
        uses: crazy-max/ghaction-github-pages@v3.0.0
        with:
          build_dir: public
          repo: jpandres/adr-tools2
          jekyll: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
